import type { CategoryMeta } from "../types/index.js";

// ─── DEFINICION COMPLETA DE LAS 17 CATEGORIAS DE TICKETS ──────────────────────
export const CATEGORIES: Record<string, CategoryMeta> = {

  reportar_usuario: {
    id: "reportar_usuario",
    label: "Reportar Usuario",
    description: "Reporta a un usuario por incumplir las normas o hacer mal uso del servidor",
    emoji: "🚫",
    modalTitle: "Reporte de Usuario",
    channelPrefix: "rep",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "usuario_reportado",
        label: "Usuario reportado",
        style: "short",
        placeholder: "Nombre, Tag o ID del usuario a reportar",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "motivo",
        label: "Motivo del reporte",
        style: "paragraph",
        placeholder: "Describe detalladamente la infracción cometida...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
      {
        customId: "pruebas",
        label: "Pruebas o evidencias",
        style: "paragraph",
        placeholder: "Proporciona enlaces, capturas o evidencia visual...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  solicitud_ck: {
    id: "solicitud_ck",
    label: "Solicitud de CK",
    description: "Solicita un CK para eliminar a tu personaje de forma permanente",
    emoji: "💀",
    modalTitle: "Solicitud de CK",
    channelPrefix: "ck",
    pingRoleIds: ["1531818941733797938", "1534292165872587024"],
    fields: [
      {
        customId: "nombre_personaje",
        label: "Nombre completo del personaje IC",
        style: "short",
        placeholder: "Nombre y apellido de tu personaje IC",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "motivo_ck",
        label: "Motivo de la solicitud de CK",
        style: "paragraph",
        placeholder: "Explica detalladamente la razón de la eliminación del personaje...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
    ],
  },

  solicitud_rp: {
    id: "solicitud_rp",
    label: "Solicitud de Roleplay",
    description: "Solicita apoyo para iniciar o coordinar una situación de RP",
    emoji: "🎭",
    modalTitle: "Solicitud de Roleplay",
    channelPrefix: "rp",
    pingRoleIds: ["1531818941733797938", "1534292165872587024"],
    fields: [
      {
        customId: "tipo_rp",
        label: "Tipo de situación de RP",
        style: "short",
        placeholder: "Ej: Evento, Tiroteo masivo, Asalto, Negociación, etc.",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "detalles_rp",
        label: "Detalles y participantes",
        style: "paragraph",
        placeholder: "Describe cómo se desarrollará la situación y qué requieren del staff...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
    ],
  },

  solicitud_rol: {
    id: "solicitud_rol",
    label: "Solicitud de Rol",
    description: "Solicita un rol específico de Discord o facción cumpliendo requisitos",
    emoji: "✨",
    modalTitle: "Solicitud de Rol",
    channelPrefix: "solrol",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "rol_solicitado",
        label: "Rol solicitado",
        style: "short",
        placeholder: "Nombre del rol de Discord",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "motivo",
        label: "Motivo de la solicitud",
        style: "paragraph",
        placeholder: "Explica el motivo por el cual solicitas este rol...",
        required: true,
        minLength: 10,
        maxLength: 800,
      },
      {
        customId: "pruebas",
        label: "Evidencia de requisitos",
        style: "paragraph",
        placeholder: "Capturas, enlaces o pruebas de cumplimiento de requisitos...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  retiro_rol: {
    id: "retiro_rol",
    label: "Retiro de Rol",
    description: "Solicita retirar un rol, personaje o situación de RP",
    emoji: "❌",
    modalTitle: "Solicitud de Retiro de Rol",
    channelPrefix: "rmrol",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "rol_a_remover",
        label: "Rol o personaje a retirar",
        style: "short",
        placeholder: "Nombre exacto del rol o situación a remover",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "motivo",
        label: "Motivo de la solicitud",
        style: "paragraph",
        placeholder: "Explica la razón por la que solicitas la remoción...",
        required: true,
        minLength: 10,
        maxLength: 800,
      },
    ],
  },

  reporte_staff: {
    id: "reporte_staff",
    label: "Reporte de Staff",
    description: "Reporta una conducta incorrecta o abuso de un miembro del Staff",
    emoji: "🛡️",
    modalTitle: "Reporte de Staff",
    channelPrefix: "rstaff",
    pingRoleIds: ["1531819188341968906", "1531821653854523412", "1538295352606593094", "1538297760686538884"],
    fields: [
      {
        customId: "staff_reportado",
        label: "Miembro del Staff reportado",
        style: "short",
        placeholder: "Nombre o Tag del staff",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "incidente",
        label: "Descripción del incidente",
        style: "paragraph",
        placeholder: "Describe lo sucedido de forma objetiva y detallada...",
        required: true,
        minLength: 20,
        maxLength: 1000,
      },
      {
        customId: "pruebas",
        label: "Pruebas visuales",
        style: "paragraph",
        placeholder: "Subes capturas o enlaces de video/audio...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  retiro_sanciones: {
    id: "retiro_sanciones",
    label: "Retiro de Sanciones",
    description: "Solicita revisar o retirar una advertencia recibida",
    emoji: "⚠️",
    modalTitle: "Apelación / Retiro de Sanción",
    channelPrefix: "sancion",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "sancion_id",
        label: "Sanción o advertencia a revisar",
        style: "short",
        placeholder: "ID de sanción, motivo o fecha en que la recibiste",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "motivo_apelacion",
        label: "Argumentos de apelación",
        style: "paragraph",
        placeholder: "Explica por qué consideras que la sanción debe ser retirada...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
    ],
  },

  soporte: {
    id: "soporte",
    label: "Soporte / Preguntas",
    description: "Para dudas, problemas o cualquier asunto general",
    emoji: "⁉️",
    modalTitle: "Soporte General",
    channelPrefix: "soporte",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "asunto",
        label: "Asunto de la consulta",
        style: "short",
        placeholder: "Resume tu duda en pocas palabras",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "descripcion",
        label: "Descripción detallada",
        style: "paragraph",
        placeholder: "Describe tu problema o pregunta con el mayor detalle posible...",
        required: true,
        minLength: 10,
        maxLength: 1000,
      },
    ],
  },

  recompensas: {
    id: "recompensas",
    label: "Recompensas / Robux / Nitro",
    description: "Reclama premios, Robux, Nitro u otras recompensas obtenidas",
    emoji: "🎁",
    modalTitle: "Reclamo de Recompensas",
    channelPrefix: "premio",
    pingRoleIds: ["1532445933785186444", "1532446141809954968"],
    fields: [
      {
        customId: "premio_ganado",
        label: "Premio o recompensa a reclamar",
        style: "short",
        placeholder: "Ej: 500 Robux, Discord Nitro, Rango VIP, etc.",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "evento_sorteo",
        label: "Evento o sorteo donde lo ganaste",
        style: "short",
        placeholder: "Nombre del sorteo o evento",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "pruebas",
        label: "Prueba de ganador",
        style: "paragraph",
        placeholder: "Link del mensaje del sorteo o captura de pantalla...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  area_rol: {
    id: "area_rol",
    label: "Área de ROL",
    description: "Solicita crear o formar parte de una facción legal / ilegal / Extranjera & Empresa",
    emoji: "📋",
    modalTitle: "Solicitud de Área de ROL",
    channelPrefix: "faccion",
    pingRoleIds: ["1532578233973739732"],
    fields: [
      {
        customId: "nombre_faccion",
        label: "Nombre de la facción o empresa",
        style: "short",
        placeholder: "Nombre oficial de la organización",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "tipo_organizacion",
        label: "Tipo (Legal / Ilegal / Extranjera / Empresa)",
        style: "short",
        placeholder: "Indica el tipo de organización",
        required: true,
        maxLength: 50,
      },
      {
        customId: "cofundador_usuario",
        label: "Co-Fundador / Usuario encargado (Opcional)",
        style: "short",
        placeholder: "Nombre, Tag o ID del Co-Fundador (Opcional)",
        required: false,
        maxLength: 100,
      },
      {
        customId: "detalles",
        label: "Lore, objetivos y lista de fundadores",
        style: "paragraph",
        placeholder: "Describe la historia, miembros iniciales y actividades...",
        required: true,
        minLength: 20,
        maxLength: 1000,
      },
    ],
  },

  control_rol: {
    id: "control_rol",
    label: "Control de Rol",
    description: "Solicitud o trámite para el control de rol",
    emoji: "⚙️",
    modalTitle: "Control de Rol",
    channelPrefix: "ctrl-rol",
    pingRoleIds: ["1531830006509076480", "1531818941733797938"],
    fields: [
      {
        customId: "solicitud",
        label: "Solicitud",
        style: "short",
        placeholder: "Describe tu solicitud",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "detalles",
        label: "Detalles",
        style: "paragraph",
        placeholder: "Describe los detalles amplios de tu solicitud...",
        required: true,
        minLength: 10,
        maxLength: 1000,
      },
    ],
  },

  robos_ic: {
    id: "robos_ic",
    label: "Robos IC",
    description: "Solicita tu dinero IC de algun robo realizado",
    emoji: "💸",
    modalTitle: "Reclamo de Robo IC",
    channelPrefix: "robo",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "monto_robo",
        label: "Monto o bienes robados",
        style: "short",
        placeholder: "Ej: $50,000 IC / Armamento / Vehículo",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "detalles_robo",
        label: "Lugar, hora e involucrados en el robo",
        style: "paragraph",
        placeholder: "Describe las circunstancias en que se llevó a cabo el robo...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
      {
        customId: "pruebas",
        label: "Pruebas del robo IC",
        style: "paragraph",
        placeholder: "Capturas, clips de video o evidencias...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  tienda: {
    id: "tienda",
    label: "Tienda del Servidor",
    description: "Consulta compras, productos y servicios disponibles en la tienda",
    emoji: "🛒",
    modalTitle: "Atención de Tienda",
    channelPrefix: "tienda",
    pingRoleIds: ["1532445933785186444", "1532446141809954968"],
    fields: [
      {
        customId: "producto_servicio",
        label: "Producto o servicio de interés",
        style: "short",
        placeholder: "Ej: Pase VIP, Robux, Vehículo exclusivo, etc.",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "detalles_compra",
        label: "Detalles o consulta de pago",
        style: "paragraph",
        placeholder: "Describe tu consulta sobre compras o método de pago...",
        required: true,
        minLength: 10,
        maxLength: 800,
      },
    ],
  },

  beneficios: {
    id: "beneficios",
    label: "Beneficios / Boosters",
    description: "Consulta los beneficios por apoyar o boostear el servidor",
    emoji: "💎",
    modalTitle: "Beneficios y Boosters",
    channelPrefix: "booster",
    pingRoleIds: ["1532445933785186444", "1532446141809954968"],
    fields: [
      {
        customId: "tipo_beneficio",
        label: "Tipo de apoyo (Booster / Donante / etc)",
        style: "short",
        placeholder: "Indica cómo has apoyado al servidor",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "detalles",
        label: "Beneficio a consultar o reclamar",
        style: "paragraph",
        placeholder: "Describe qué beneficio deseas recibir o tu consulta...",
        required: true,
        minLength: 10,
        maxLength: 800,
      },
    ],
  },

  solicitud_promo: {
    id: "solicitud_promo",
    label: "Solicitud de Promoción",
    description: "Solicita autorización para promocionar tu contenido o comunidad",
    emoji: "📰",
    modalTitle: "Solicitud de Promoción",
    channelPrefix: "promo",
    pingRoleIds: ["1534292165872587024", "1534292128178376794"],
    fields: [
      {
        customId: "canal_contenido",
        label: "Plataforma y canal de contenido",
        style: "short",
        placeholder: "Enlace o nombre de tu canal / contenido",
        required: true,
        minLength: 5,
        maxLength: 200,
      },
      {
        customId: "propuesta",
        label: "Propuesta de colaboración / difusión",
        style: "paragraph",
        placeholder: "Explica qué tipo de promoción deseas realizar y qué ofreces...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
    ],
  },

  alianza: {
    id: "alianza",
    label: "Alianza Comunitaria",
    description: "Solicita una alianza con nuestro servidor o comunidad",
    emoji: "🤝",
    modalTitle: "Solicitud de Alianza",
    channelPrefix: "alianza",
    pingRoleIds: ["1534292165872587024", "1534292128178376794"],
    fields: [
      {
        customId: "nombre_comunidad",
        label: "Nombre de tu servidor o comunidad",
        style: "short",
        placeholder: "Nombre oficial de tu comunidad",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "enlace_invitacion",
        label: "Enlace de invitación o web",
        style: "short",
        placeholder: "https://discord.gg/ejemplo",
        required: true,
        minLength: 5,
        maxLength: 200,
      },
      {
        customId: "miembros_activos",
        label: "Cantidad de miembros y actividad",
        style: "paragraph",
        placeholder: "Número de usuarios, temática y propuesta de alianza...",
        required: true,
        minLength: 15,
        maxLength: 800,
      },
    ],
  },

  propuesta_evento: {
    id: "propuesta_evento",
    label: "Propuesta de Evento",
    description: "Propón un evento o actividad para la comunidad",
    emoji: "🎉",
    modalTitle: "Propuesta de Evento",
    channelPrefix: "evento",
    pingRoleIds: ["1534292165872587024", "1534292128178376794"],
    fields: [
      {
        customId: "nombre_evento",
        label: "Nombre del evento propuesto",
        style: "short",
        placeholder: "Título atractivo para el evento",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "descripcion_evento",
        label: "Dinámica, fecha estimada y premios",
        style: "paragraph",
        placeholder: "Describe en qué consiste el evento y el apoyo que requieres...",
        required: true,
        minLength: 20,
        maxLength: 1000,
      },
    ],
  },

  otros: {
    id: "otros",
    label: "Otros",
    description: "Para cualquier solicitud que no tenga una categoría específica",
    emoji: "➕",
    modalTitle: "Solicitud General",
    channelPrefix: "otro",
    pingRoleIds: ["1531834575796310096", "1534292165872587024"],
    fields: [
      {
        customId: "asunto",
        label: "Asunto de la consulta",
        style: "short",
        placeholder: "Resume el tema de tu solicitud",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "descripcion",
        label: "Descripción detallada",
        style: "paragraph",
        placeholder: "Explica tu situación con la mayor claridad posible...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
    ],
  },

  reporte_desarrollo: {
    id: "reporte_desarrollo",
    label: "Reporte Desarrollo",
    description: "Para reportar fallas en el funcionamiento técnico del server / BOT",
    emoji: "💻",
    modalTitle: "Reporte de Desarrollo / BOT",
    channelPrefix: "dev",
    pingRoleIds: ["1538429214158495824", "1534292523365826661"],
    fields: [
      {
        customId: "sistema_fallo",
        label: "Comando, sistema o función con falla",
        style: "short",
        placeholder: "Ej: /multas, verificación OAuth, economía, etc.",
        required: true,
        minLength: 3,
        maxLength: 150,
      },
      {
        customId: "descripcion_bug",
        label: "Descripción del error técnico",
        style: "paragraph",
        placeholder: "Describe los pasos para reproducir la falla o qué ocurrió...",
        required: true,
        minLength: 15,
        maxLength: 1000,
      },
      {
        customId: "pruebas",
        label: "Capturas o evidencias del error",
        style: "paragraph",
        placeholder: "Enlace a imágenes o capturas de la falla...",
        required: false,
        maxLength: 500,
      },
    ],
  },

} as const;

export const CATEGORY_ORDER: string[] = [
  "reportar_usuario",
  "solicitud_ck",
  "solicitud_rp",
  "solicitud_rol",
  "retiro_rol",
  "reporte_staff",
  "retiro_sanciones",
  "soporte",
  "recompensas",
  "area_rol",
  "control_rol",
  "robos_ic",
  "tienda",
  "beneficios",
  "solicitud_promo",
  "alianza",
  "propuesta_evento",
  "otros",
  "reporte_desarrollo",
];
