import type { CategoryMeta } from "../types/index.js";

// ─── DEFINICION COMPLETA DE CATEGORIAS ────────────────────────────────────────
// Cada categoria tiene su propio modal con campos especificos
export const CATEGORIES: Record<string, CategoryMeta> = {

  reportar: {
    id: "reportar",
    label: "Reportar",
    description: "Informa sobre un jugador que incumplió las normas",
    emoji: "🛡️",
    modalTitle: "Reporte de Usuario",
    channelPrefix: "rep",
    fields: [
      {
        customId: "usuario_reportado",
        label: "Usuario reportado",
        style: "short",
        placeholder: "Nombre#0000 o ID del usuario",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "motivo",
        label: "Motivo del reporte",
        style: "paragraph",
        placeholder: "Describe detalladamente el motivo del reporte...",
        required: true,
        minLength: 20,
        maxLength: 1000,
      },
      {
        customId: "pruebas",
        label: "Pruebas (links de imagenes, capturas, etc.)",
        style: "paragraph",
        placeholder: "Proporciona enlaces o descripcion de tus pruebas...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  reportar_staff: {
    id: "reportar_staff",
    label: "Reportar Staff",
    description: "Reporta un problema con un miembro del equipo",
    emoji: "👮",
    modalTitle: "Reporte de Staff",
    channelPrefix: "rstaff",
    fields: [
      {
        customId: "staff_reportado",
        label: "Staff reportado",
        style: "short",
        placeholder: "Nombre del miembro del staff",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "incidente",
        label: "Descripcion del incidente",
        style: "paragraph",
        placeholder: "Describe el comportamiento inadecuado del staff...",
        required: true,
        minLength: 30,
        maxLength: 1000,
      },
      {
        customId: "fecha_hora",
        label: "Fecha y hora aproximada del incidente",
        style: "short",
        placeholder: "Ej: 21/07/2026 a las 20:00",
        required: true,
        maxLength: 100,
      },
      {
        customId: "pruebas",
        label: "Pruebas o testigos",
        style: "paragraph",
        placeholder: "Pruebas visuales, capturas, o nombres de testigos...",
        required: false,
        maxLength: 500,
      },
    ],
  },

  peticion_rol: {
    id: "peticion_rol",
    label: "Petición de Rol",
    description: "Solicita un rol y adjunta pruebas o requisitos",
    emoji: "📋",
    modalTitle: "Peticion de Rol",
    channelPrefix: "rol",
    fields: [
      {
        customId: "rol_solicitado",
        label: "Rol que solicitas",
        style: "short",
        placeholder: "Nombre exacto del rol que deseas",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "motivo",
        label: "Motivo de la solicitud",
        style: "paragraph",
        placeholder: "Explica por que mereces o necesitas este rol...",
        required: true,
        minLength: 20,
        maxLength: 800,
      },
      {
        customId: "pruebas",
        label: "Pruebas o requisitos cumplidos",
        style: "paragraph",
        placeholder: "Proporciona capturas, links o evidencia de los requisitos...",
        required: true,
        minLength: 10,
        maxLength: 500,
      },
    ],
  },

  reporte_invisible: {
    id: "reporte_invisible",
    label: "Reporte Invisible",
    description: "Envía un reporte confidencial cuando lo requieras",
    emoji: "👁️",
    modalTitle: "Reporte Confidencial",
    channelPrefix: "conf",
    fields: [
      {
        customId: "situacion",
        label: "Situacion a reportar",
        style: "paragraph",
        placeholder: "Describe la situacion de forma confidencial. Solo el staff con acceso especial podra ver esto.",
        required: true,
        minLength: 30,
        maxLength: 1000,
      },
      {
        customId: "involucrados",
        label: "Personas involucradas (opcional)",
        style: "short",
        placeholder: "Nombres de los involucrados si deseas mencionarlos",
        required: false,
        maxLength: 200,
      },
      {
        customId: "urgencia",
        label: "Nivel de urgencia",
        style: "short",
        placeholder: "Baja / Media / Alta / Critica",
        required: true,
        maxLength: 20,
      },
    ],
  },

  remover_rol: {
    id: "remover_rol",
    label: "Remover Rol",
    description: "Solicita que se retire un rol cuando corresponda",
    emoji: "🎭",
    modalTitle: "Solicitud de Remocion de Rol",
    channelPrefix: "rmrol",
    fields: [
      {
        customId: "rol_a_remover",
        label: "Rol que deseas que se te retire",
        style: "short",
        placeholder: "Nombre exacto del rol",
        required: true,
        minLength: 2,
        maxLength: 100,
      },
      {
        customId: "razon",
        label: "Razon de la solicitud",
        style: "paragraph",
        placeholder: "Explica por que deseas que se te retire este rol...",
        required: true,
        minLength: 15,
        maxLength: 800,
      },
    ],
  },

  compras_reales: {
    id: "compras_reales",
    label: "IRL",
    description: "Soporte para compras con dinero real o Robux",
    emoji: "💵",
    modalTitle: "Gestion de Compra Real",
    channelPrefix: "compra",
    fields: [
      {
        customId: "tipo_compra",
        label: "Tipo de compra",
        style: "short",
        placeholder: "Ej: Donacion, VIP, Rang, Robux, etc.",
        required: true,
        maxLength: 100,
      },
      {
        customId: "monto",
        label: "Monto / Cantidad",
        style: "short",
        placeholder: "Ej: $5 USD / 1000 Robux",
        required: true,
        maxLength: 50,
      },
      {
        customId: "comprobante",
        label: "Comprobante de pago (link o descripcion)",
        style: "paragraph",
        placeholder: "Adjunta el link de la captura o describe el comprobante...",
        required: true,
        minLength: 10,
        maxLength: 500,
      },
      {
        customId: "que_esperas",
        label: "Que esperas recibir",
        style: "paragraph",
        placeholder: "Describe que beneficio, rol o item debes recibir...",
        required: true,
        minLength: 10,
        maxLength: 400,
      },
    ],
  },

  reclamar_sorteos: {
    id: "reclamar_sorteos",
    label: "Reclamar Sorteo",
    description: "Reclama el premio de un sorteo que hayas ganado",
    emoji: "🎁",
    modalTitle: "Reclamacion de Premio",
    channelPrefix: "sorteo",
    fields: [
      {
        customId: "sorteo",
        label: "Sorteo o evento ganado",
        style: "short",
        placeholder: "Nombre del sorteo o descripcion del evento",
        required: true,
        minLength: 3,
        maxLength: 200,
      },
      {
        customId: "premio",
        label: "Premio ganado",
        style: "short",
        placeholder: "Describe el premio que ganaste",
        required: true,
        minLength: 3,
        maxLength: 200,
      },
      {
        customId: "prueba_ganador",
        label: "Prueba de que ganaste (link de mensaje, captura, etc.)",
        style: "paragraph",
        placeholder: "Proporciona evidencia de que eres el ganador...",
        required: true,
        minLength: 10,
        maxLength: 500,
      },
    ],
  },

  empresas_faccion: {
    id: "empresas_faccion",
    label: "Empresas y Facciones",
    description: "Crea una empresa, facción o solicita ayuda",
    emoji: "🤝",
    modalTitle: "Solicitud de Empresa o Faccion",
    channelPrefix: "empresa",
    fields: [
      {
        customId: "nombre",
        label: "Nombre de la empresa o faccion",
        style: "short",
        placeholder: "Nombre oficial de tu organizacion",
        required: true,
        minLength: 3,
        maxLength: 100,
      },
      {
        customId: "tipo",
        label: "Tipo de organizacion",
        style: "short",
        placeholder: "Empresa / Faccion / Clan / Cartel / etc.",
        required: true,
        maxLength: 50,
      },
      {
        customId: "descripcion",
        label: "Descripcion",
        style: "paragraph",
        placeholder: "Describe el proposito, actividades y objetivos de tu organizacion...",
        required: true,
        minLength: 30,
        maxLength: 800,
      },
      {
        customId: "miembros",
        label: "Miembros fundadores",
        style: "paragraph",
        placeholder: "Lista los nombres de los miembros iniciales de tu organizacion...",
        required: false,
        maxLength: 400,
      },
    ],
  },

  otro: {
    id: "otro",
    label: "Otros",
    description: "Si tu consulta no encaja en ninguna categoría",
    emoji: "📦",
    modalTitle: "Consulta General",
    channelPrefix: "otro",
    fields: [
      {
        customId: "asunto",
        label: "Asunto",
        style: "short",
        placeholder: "Resume brevemente tu consulta",
        required: true,
        minLength: 3,
        maxLength: 200,
      },
      {
        customId: "descripcion",
        label: "Descripcion detallada",
        style: "paragraph",
        placeholder: "Explica tu situacion o consulta con el mayor detalle posible...",
        required: true,
        minLength: 20,
        maxLength: 1000,
      },
    ],
  },

  dudas_general: {
    id: "dudas_general",
    label: "Dudas Generales",
    description: "Haz cualquier pregunta sobre el servidor",
    emoji: "💬",
    modalTitle: "Duda General",
    channelPrefix: "duda",
    fields: [
      {
        customId: "pregunta",
        label: "Tu pregunta",
        style: "paragraph",
        placeholder: "Escribe tu duda o pregunta aqui. Intentaremos ayudarte lo mas pronto posible...",
        required: true,
        minLength: 10,
        maxLength: 1000,
      },
      {
        customId: "contexto",
        label: "Contexto adicional (opcional)",
        style: "paragraph",
        placeholder: "Cualquier informacion adicional que nos ayude a entender mejor tu situacion...",
        required: false,
        maxLength: 500,
      },
    ],
  },

} as const;

export const CATEGORY_ORDER: string[] = [
  "reportar",
  "reportar_staff",
  "peticion_rol",
  "reporte_invisible",
  "remover_rol",
  "compras_reales",
  "reclamar_sorteos",
  "empresas_faccion",
  "otro",
  "dudas_general",
];
